---
- name: Configure Elk VM with Docker
  hosts: elk
  become: true
  tasks:
    # Install Docker.io
    - name: Install docker.io
      apt:
        update_cache: yes
        force_apt_get: yes
        name: docker.io
        state: present

    # Install Python3-pip
    - name: Install python3-pip
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    # Uses pip3 module to setup Docker
    - name: Install Docker Module
      pip:
        name: docker
        state: present

    # Command To Increase Memory
    - name: Increase Virtual Memory
      command: sysctl -w vm.max_map_count=262144

    # Use Sysctl to Use More Memory
    - name: Uses More Memory
      sysctl:
        name: vm.max_map_count
        value: 262144
        state: present
        reload: yes

    # Uses Docker Container Module
    - name: Download Elk Container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        # Configured Elk Stack Port Mapping to following Ports:
        published_ports:
          -  5601:5601
          -  9200:9200
          -  5044:5044

    # Use the Ansible module systemd to make sure the docker service is running.
    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes
